apiVersion: v1 
kind: Pod
metadata:
  name: baturu01
  namespace: default
spec:
  containers:
  - name: baturu01
    image: nginx:1.14.2
    command: ["/bin/sh"]
    args: ["-c", "sleep 300000"]
    volumeMounts: 
    - mountPath: /mnt
      name: hostfs
  volumes:
  - name: hostfs
    hostPath:  
      path: /
  automountServiceAccountToken: true
  hostNetwork: true